name: 'Pre Release Tags'

on:
  pull_request:
    branches: [ master ]

jobs:
  comment:
    runs-on: ubuntu-latest
    if: github.event.action == 'opened'

    steps:
      - name: Check Branch
        if: github.event.pull_request.head.ref != 'develop'
        run: exit 1

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Node
        uses: actions/setup-node@v1

      - name: Intall Dependencies
        run: yarn install

      - name: Check User
        id: is-member
        uses: codistica/actions/is-member@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          org: codistica
          username: ${{ github.event.pull_request.user.login }}
          throwError: false

      - name: Get Tags
        if: steps.is-member.outputs.result == '1'
        id: tags
        uses: codistica/actions/monorepo-release-tags@v1
        with:
          token: ${{ secrets.CODISTIBOT_TOKEN }}
          monorepo-name: "@codistica"
          check-only: true

      - name: Comment New Tags
        if: |
          steps.is-member.outputs.result == '1' &&
          steps.tags.outputs.tags != '0'
        uses: codistica/actions/comment@v1
        with:
          token: ${{ secrets.CODISTIBOT_TOKEN }}
          number: ${{ github.event.pull_request.number }}
          comment: >
            Greetings @${{ github.event.pull_request.user.login }},

            My circuits will create this/these release/s:

            ${{ steps.tags.outputs.tags }}.


            codistibot.

      - name: Comment No New Tags
        if: |
          steps.is-member.outputs.result == '1' &&
          steps.tags.outputs.tags == '0'
        uses: codistica/actions/comment@v1
        with:
          token: ${{ secrets.CODISTIBOT_TOKEN }}
          number: ${{ github.event.pull_request.number }}
          comment: >
            Greetings @${{ github.event.pull_request.user.login }},

            My sensors have detected this release will not generate new tags.
            If this is expected, go ahead with the merge!. Otherwise, be sure you have updated
            the versions you want to release.


            codistibot.
