name: 'Pull Request'

on:
  pull_request:
    branches: [ develop ]
    types: [ opened, synchronize ]

jobs:
  labels:
    name: Update Labels
    runs-on: ubuntu-latest
    steps:
      - name: Update Labels
        uses: codistica/actions/label@v1
        with:
          token: ${{ secrets.CODISTIBOT_TOKEN }}
          number: ${{ github.event.pull_request.number }}
          labels: '["⏳ pending"]'

  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1

      - name: Install Dependencies
        run: yarn install

      - name: Build All
        run: yarn run build

      - name: Test
        run: yarn run test

      - name: Create Coverage File
        run: yarn run coverage

      - name: Report Coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
