name: 'Release Tags'

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1

      - name: Intall dependencies
        run: yarn install

      - name: Check User
        id: is-member
        uses: codistica/actions/is-member@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          org: codistica
          username: ${{ github.event.sender.login }}
          throwError: false

      - name: Add Release Tags
        if: steps.is-member.outputs.result == '1'
        id: tags
        uses: codistica/actions/monorepo-release-tags@v1
        with:
          token: ${{ secrets.CODISTIBOT_TOKEN }}
          monorepo-name: '@codistica'
